#!/bin/bash

if [[ $(uname -m) == "arm64" ]]; then
    export SELENIUM_IMAGE="seleniarm/hub:4.4.0-20220903"
else
    export SELENIUM_IMAGE="selenium/standalone-chrome:latest"
fi

/usr/local/bin/docker-compose "$@"
